name: CD - Deploy to GKE

on:
  workflow_run:
    workflows: ["CI - Build & Scan"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: <gcp-project-id>
  ARTIFACT_REGION: <artifact-region>
  GKE_ZONE: <gke-zone>
  REPO_NAME: <artifact-repository-name>
  IMAGE_NAME: <image-name>
  CLUSTER_NAME: <gke-cluster-name>

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate to Google Cloud via OIDC
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/<project-number>/locations/global/workloadIdentityPools/<pool-name>/providers/<provider-name>"
          service_account: "<service-account>@<project-id>.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # Install GKE Auth Plugin
      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      # Get Cluster Credentials
      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME \
            --zone $GKE_ZONE \
            --project $PROJECT_ID

      # Install OPA Gatekeeper
      - name: Install Gatekeeper
        run: |
          kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.14/deploy/gatekeeper.yaml
          kubectl rollout status deployment/gatekeeper-controller-manager \
            -n gatekeeper-system --timeout=180s

      # Apply Templates
      - name: Apply Constraint Templates
        run: |
          kubectl apply -f policy-templates/

      # Wait for CRDs
      - name: Wait for CRDs
        run: |
          kubectl wait --for=condition=Established crd --all --timeout=90s

      # Apply Constraints
      - name: Apply Constraints
        run: |
          kubectl apply -f policy-constraints/

      # Deploy Application (Immutable SHA tag)
      - name: Deploy Application
        run: |
          IMAGE=$ARTIFACT_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.event.workflow_run.head_sha }}

          kubectl set image deployment/<deployment-name> \
            <container-name>=$IMAGE --record || true

          kubectl apply -f k8s/

      # Verify Rollout
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/<deployment-name> --timeout=180s