name: CI - Build & Scan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write   # Required for OIDC

env:
  PROJECT_ID: cloudside-academy
  REGION: us-central1
  REPO_NAME: rohith-task          # Artifact Registry repo name (NOT cluster name)
  IMAGE_NAME: rohith-devsecops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate using OIDC
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/769170094354/locations/global/workloadIdentityPools/github-action-pool/providers/github-actions-provider"
          service_account: "rohith-wif@cloudside-academy.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # Build Docker Image (IMPORTANT: ./app)
      - name: Build Docker Image
        run: |
          docker build \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }} \
            ./app

      # Scan Image with Trivy (clean method)
      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL

      # Push Image
      - name: Push Docker Image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }}
