name: CI - Build & Scan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write   # Required for OIDC authentication

env:
  PROJECT_ID: <gcp-project-id>
  REGION: <artifact-region>
  REPO_NAME: <artifact-repository-name>
  IMAGE_NAME: <image-name>

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using OIDC
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/<project-number>/locations/global/workloadIdentityPools/<pool-name>/providers/<provider-name>"
          service_account: "<service-account>@<project-id>.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }} .

      # Scan Image using Trivy
      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL

      # Push Image only if Scan Passes
      - name: Push Docker Image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }}